Update intruduced by kernel_dev

diff --git a/trunk/src/dump/h5lsserie.in b/trunk/src/dump/h5lsserie.in
--- a/trunk/src/dump/h5lsserie.in
+++ b/trunk/src/dump/h5lsserie.in
@@ -1,31 +1,31 @@
-#! /usr/bin/python
+#! /bin/sh
 
-import os
-import re
-import sys
+H=0
+D=0
+L=0
+while test $# -ne 0; do
+  case $1 in
+    -d)        D=1;;
+    -h|--help) H=1;;
+    -l)        L=1;;
+    -*)        echo "Invalid option: $1; see output of h5lsserie"
+               exit 1;;
+    *)         FILE=$1;;
+  esac
+  shift
+done
 
-if len(sys.argv)!=2:
-  print 'Usage h5lsserie <filename>'
+if [ $H -eq 1 ]; then
+  echo "Lists the groups and datasets in a hdf5 file."
+  echo ""
+  echo "Usage:"
+  echo "  h5lsserie [-d] [-l] <file.h5>"
+  echo "    -h, --help: Show this help"
+  echo "    -d:         Show 'Description' attribute"
+  echo "    -l:         Show 'Column Label' attribute"
+  exit 0
+fi
 
-result=os.popen('@h5ls@ -rv '+sys.argv[1]).read()
-line=result.split('\n')
-for i in range(0,len(line)):
-  if re.match('^/',line[i]):
-    print line[i]
-  if re.match('^ +Attribute: +Description +scalar$',line[i]):
-    print '    Description:',
-    print re.sub('^.*"([^"]*)".*$',r'\1',line[i+2])
+prefix=@prefix@
 
-#  # Output "Meber Labels" and "Column Labels" (ALPHA)
-#  if re.match('^ +Type: +struct +{',line[i]):
-#    print '    Member Labels:'
-#    j=0
-#    while 1<2:
-#      j=j+1
-#      if re.match('^ +}',line[i+j]):
-#        break
-#      print '        '+re.sub('^.*"([^"]*)".*$',r'\1',line[i+j])
-#  if re.match('^ +Attribute: +Column\\\ Label ',line[i]):
-#    print '    Column Label:'
-#    print '        ',
-#    print re.sub('^[^"]*(".*").*$',r'\1',line[i+2])
+@h5dump@ -xA $FILE | xsltproc -param FILENAME "'$FILE'" -param LABEL $L -param DESCRIPTION $D @datadir@/hdf5serie/xsl/h5lsserie.xsl -
